# Generated by Django 4.1 on 2022-08-15 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_des', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=100)),
                ('created_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
